-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\ksmra\Documents\MATLAB\codegen\iir_IP\hdlsrc\BiquadDF2Section1.vhd
-- Created: 2026-01-06 17:34:18
-- 
-- Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: BiquadDF2Section1
-- Source Path: iir_IP/dsphdl.BiquadFilter/BiquadDF2Section1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY BiquadDF2Section1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validOut                          :   OUT   std_logic
        );
END BiquadDF2Section1;


ARCHITECTURE rtl OF BiquadDF2Section1 IS

  -- Signals
  SIGNAL dataIn_signed                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL inReg                            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL inValidReg                       : std_logic;
  SIGNAL state1                           : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL state2                           : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL denProd2                         : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL denOut                           : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL denProd1                         : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL adder_add_cast                   : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL adder_add_cast_1                 : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL denSum2                          : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL adder_add_cast_2                 : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL denSum1                          : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL numPrePipe1                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL numProd1                         : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL numPostPipe1                     : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL numPostPipe1Dly                  : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL numPrePipe2                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL gain_cast                        : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL gain_cast_1                      : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL numProd2                         : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL numPostPipe2                     : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL numPrePipe3                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL numProd3                         : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL numPostPipe3                     : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL adder_add_cast_3                 : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL adder_add_cast_4                 : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL numSum2                          : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL numSum2Dly                       : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL adder_add_cast_5                 : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL numSum1                          : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL numSumReg_1                      : signed(34 DOWNTO 0);  -- sfix35_En23
  SIGNAL convertOut                       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL dataOut_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL intdelay_reg                     : std_logic_vector(5 DOWNTO 0);  -- ufix1 [6]

BEGIN
  dataIn_signed <= signed(dataIn);

  InRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        inReg <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        inReg <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS InRegister_process;


  InValidRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        inValidReg <= '0';
      ELSIF enb = '1' THEN
        inValidReg <= validIn;
      END IF;
    END IF;
  END PROCESS InValidRegister_process;


  State2Reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        state2 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' AND inValidReg = '1' THEN
        state2 <= state1;
      END IF;
    END IF;
  END PROCESS State2Reg_process;


  denProd2 <= to_signed(-16#34D7#, 16) * state2;

  State1Reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        state1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' AND inValidReg = '1' THEN
        state1 <= denOut;
      END IF;
    END IF;
  END PROCESS State1Reg_process;


  denProd1 <= to_signed(16#7FFF#, 16) * state1;

  adder_add_cast <= resize(denProd1, 35);
  adder_add_cast_1 <= resize(denProd2, 35);
  denSum2 <= adder_add_cast + adder_add_cast_1;

  adder_add_cast_2 <= resize(inReg & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 35);
  denSum1 <= adder_add_cast_2 + denSum2;

  
  denOut <= X"7FFF" WHEN (denSum1(34) = '0') AND (denSum1(33 DOWNTO 30) /= "0000") ELSE
      X"8000" WHEN (denSum1(34) = '1') AND (denSum1(33 DOWNTO 30) /= "1111") ELSE
      denSum1(30 DOWNTO 15);

  numPreReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPrePipe1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        numPrePipe1 <= denOut;
      END IF;
    END IF;
  END PROCESS numPreReg1_process;


  numProd1 <= to_signed(16#7FFF#, 16) * numPrePipe1;

  numPostReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPostPipe1 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        numPostPipe1 <= numProd1;
      END IF;
    END IF;
  END PROCESS numPostReg1_process;


  numDlyReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPostPipe1Dly <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        numPostPipe1Dly <= numPostPipe1;
      END IF;
    END IF;
  END PROCESS numDlyReg1_process;


  numPreReg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPrePipe2 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        numPrePipe2 <= state1;
      END IF;
    END IF;
  END PROCESS numPreReg2_process;


  gain_cast <= resize(numPrePipe2, 17);
  gain_cast_1 <=  - (gain_cast);
  numProd2 <= gain_cast_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  numPostReg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPostPipe2 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        numPostPipe2 <= numProd2;
      END IF;
    END IF;
  END PROCESS numPostReg2_process;


  numPreReg3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPrePipe3 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        numPrePipe3 <= state2;
      END IF;
    END IF;
  END PROCESS numPreReg3_process;


  numProd3 <= to_signed(16#34D7#, 16) * numPrePipe3;

  numPostReg3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPostPipe3 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        numPostPipe3 <= numProd3;
      END IF;
    END IF;
  END PROCESS numPostReg3_process;


  adder_add_cast_3 <= resize(numPostPipe2, 35);
  adder_add_cast_4 <= resize(numPostPipe3, 35);
  numSum2 <= adder_add_cast_3 + adder_add_cast_4;

  numSumDlyReg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numSum2Dly <= to_signed(0, 35);
      ELSIF enb = '1' THEN
        numSum2Dly <= numSum2;
      END IF;
    END IF;
  END PROCESS numSumDlyReg2_process;


  adder_add_cast_5 <= resize(numPostPipe1Dly, 35);
  numSum1 <= adder_add_cast_5 + numSum2Dly;

  numSumReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numSumReg_1 <= to_signed(0, 35);
      ELSIF enb = '1' THEN
        numSumReg_1 <= numSum1;
      END IF;
    END IF;
  END PROCESS numSumReg_process;


  
  convertOut <= X"7FFF" WHEN (numSumReg_1(34) = '0') AND (numSumReg_1(33 DOWNTO 23) /= "00000000000") ELSE
      X"8000" WHEN (numSumReg_1(34) = '1') AND (numSumReg_1(33 DOWNTO 23) /= "11111111111") ELSE
      numSumReg_1(23 DOWNTO 8);

  outputReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataOut_tmp <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        dataOut_tmp <= convertOut;
      END IF;
    END IF;
  END PROCESS outputReg_process;


  dataOut <= std_logic_vector(dataOut_tmp);

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        intdelay_reg(0) <= validIn;
        intdelay_reg(5 DOWNTO 1) <= intdelay_reg(4 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_process;

  validOut <= intdelay_reg(5);

END rtl;

